export const sub3data7 = [
  { subject: "資訊處理", agency: "基隆市衛生局", count: "1"},
  { subject: "資訊處理", agency: "新竹市政府", count: "1"},
  { subject: "資訊處理", agency: "臺北市政府交通局", count: "1"},
  { subject: "資訊處理", agency: "桃園市政府智慧城鄉發展委員會", count: "1"},
  { subject: "資訊處理", agency: "桃園市政府智慧城鄉發展委員會", count: "1"},
  { subject: "資訊處理", agency: "桃園市政府智慧城鄉發展委員會", count: "1"},
  { subject: "資訊處理", agency: "桃園市政府智慧城鄉發展委員會", count: "1"},
  { subject: "資訊處理", agency: "新北市政府消防局", count: "1"},
  { subject: "資訊處理", agency: "臺中市政府數位發展局", count: "1"},
  { subject: "資訊處理", agency: "高雄市政府資訊處", count: "1"},
  { subject: "資訊處理", agency: "內政部警政署刑事警察局", count: "2"},
  { subject: "資訊處理", agency: "內政部警政署警察機械修理廠", count: "1"},
  { subject: "資訊處理", agency: "內政部警政署警察廣播電臺", count: "1"},
  { subject: "資訊處理", agency: "財政部財政資訊中心", count: "1"},
  { subject: "資訊處理", agency: "國立臺東大學附屬特殊教育學校", count: "1"},
  { subject: "資訊處理", agency: "國立竹北高級中學", count: "1"},
  { subject: "資訊處理", agency: "國立花蓮特殊教育學校", count: "1"},
  { subject: "資訊處理", agency: "臺灣臺北地方檢察署", count: "1"},
  { subject: "資訊處理", agency: "臺灣桃園地方檢察署", count: "1"},
  { subject: "資訊處理", agency: "經濟部智慧財產局", count: "1"},
  { subject: "資訊處理", agency: "交通部公路局臺北市區監理所", count: "1"},
  { subject: "資訊處理", agency: "交通部高速公路局", count: "1"},
  { subject: "資訊處理", agency: "勞動部勞工保險局", count: "12"},
  { subject: "資訊處理", agency: "衛生福利部食品藥物管理署", count: "1"},
  { subject: "資訊處理", agency: "衛生福利部中央健康保險署", count: "4"},
  { subject: "資訊處理", agency: "衛生福利部中央健康保險署", count: "1"},
  { subject: "資訊處理", agency: "國家發展委員會檔案管理局", count: "2"},
  { subject: "資訊處理", agency: "國家科學及技術委員會", count: "1"},
  { subject: "資訊處理", agency: "國軍退除役官兵輔導委員會", count: "1"},
  { subject: "資訊處理", agency: "行政院主計總處主計資訊處", count: "2"},
  { subject: "資訊處理", agency: "臺灣高等法院", count: "1"},
  { subject: "資訊處理", agency: "臺灣臺北地方法院", count: "1"},
  { subject: "資訊處理", agency: "臺灣基隆地方法院", count: "1"},
  { subject: "資訊處理", agency: "監察院", count: "1" },
];
